In [13]:
# ==========================================
# FINAL DATA INTEGRITY CHECK
# ==========================================

# 1. Duplicate disease-symptom pairs
pair_duplicates = disease_symptoms.duplicated(
    subset=["disease_id", "symptom_id"]
).sum()

print("1. Duplicate disease-symptom pairs:", pair_duplicates)


# 2. Matrix symptom columns
matrix_id_columns = ["disease_id", "disease_name"]

matrix_symptom_columns = [
    col for col in matrix.columns
    if col not in matrix_id_columns
]

print("\n2. Number of symptom columns:", len(matrix_symptom_columns))
print("   First 10:", matrix_symptom_columns[:10])


# 3. Matrix values
matrix_values = matrix[matrix_symptom_columns]

unique_values = set(matrix_values.stack().unique())

print("\n3. Unique values in symptom matrix:")
print("  ", sorted(unique_values))


# 4. Disease IDs in matrix
matrix_disease_ids = set(matrix["disease_id"])

missing_from_matrix = disease_ids - matrix_disease_ids
extra_in_matrix = matrix_disease_ids - disease_ids

print("\n4. Disease ID check")
print("   Diseases missing from matrix:", len(missing_from_matrix))
print("   Unknown diseases in matrix:", len(extra_in_matrix))


# 5. Symptom IDs in matrix
matrix_symptom_ids = set(matrix_symptom_columns)

missing_symptoms = symptom_ids - matrix_symptom_ids
extra_symptoms = matrix_symptom_ids - symptom_ids

print("\n5. Symptom ID check")
print("   Symptoms missing from matrix:", len(missing_symptoms))
print("   Unknown symptoms in matrix:", len(extra_symptoms))


# 6. Final summary
print("\n==========================================")
print("FINAL VALIDATION SUMMARY")
print("==========================================")

checks = {
    "Duplicate disease-symptom pairs": pair_duplicates == 0,
    "Matrix has 151 symptoms": len(matrix_symptom_columns) == len(symptom_ids),
    "Matrix values are only 0/1": unique_values <= {0, 1},
    "All diseases exist in matrix": len(missing_from_matrix) == 0 and len(extra_in_matrix) == 0,
    "All symptoms exist in matrix": len(missing_symptoms) == 0 and len(extra_symptoms) == 0,
}

for check, passed in checks.items():
    print(("✓" if passed else "✗"), check)

1. Duplicate disease-symptom pairs: 0

2. Number of symptom columns: 151
   First 10: ['S001', 'S002', 'S003', 'S004', 'S005', 'S006', 'S007', 'S008', 'S009', 'S010']

3. Unique values in symptom matrix:
   [np.int64(0), np.int64(1)]

4. Disease ID check
   Diseases missing from matrix: 0
   Unknown diseases in matrix: 0

5. Symptom ID check
   Symptoms missing from matrix: 0
   Unknown symptoms in matrix: 0

==========================================
FINAL VALIDATION SUMMARY
==========================================
✓ Duplicate disease-symptom pairs
✓ Matrix has 151 symptoms
✓ Matrix values are only 0/1
✓ All diseases exist in matrix
✓ All symptoms exist in matrix

In [12]:
print(
    disease_symptoms["association"]
    .value_counts(dropna=False)
)

association
1    243
Name: count, dtype: int64

In [11]:
pair_duplicates = disease_symptoms.duplicated(
    subset=["disease_id", "symptom_id"]
).sum()

print("Duplicate disease-symptom pairs:", pair_duplicates)

Duplicate disease-symptom pairs: 0

In [10]:
# ==========================================
# DISEASE-SYMPTOM RELATIONSHIP VALIDATION
# ==========================================

# 1. Check disease IDs
disease_ids = set(diseases["disease_id"])

# 2. Check symptom IDs
symptom_ids = set(symptoms["symptom_id"])

# 3. IDs used in disease_symptoms.csv
relationship_disease_ids = set(disease_symptoms["disease_id"])
relationship_symptom_ids = set(disease_symptoms["symptom_id"])

# 4. Find invalid references
invalid_disease_ids = relationship_disease_ids - disease_ids
invalid_symptom_ids = relationship_symptom_ids - symptom_ids

print("=== RELATIONSHIP CHECK ===")

print("Invalid disease IDs:",
      len(invalid_disease_ids))

print("Invalid symptom IDs:",
      len(invalid_symptom_ids))

if invalid_disease_ids:
    print("Invalid disease IDs:", invalid_disease_ids)

if invalid_symptom_ids:
    print("Invalid symptom IDs:", invalid_symptom_ids)

=== RELATIONSHIP CHECK ===
Invalid disease IDs: 0
Invalid symptom IDs: 0

In [9]:
print("DISEASES")
print(diseases.columns.tolist())

print("\nSYMPTOMS")
print(symptoms.columns.tolist())

print("\nDISEASE-SYMPTOMS")
print(disease_symptoms.columns.tolist())

print("\nMATRIX")
print(matrix.columns.tolist())

DISEASES
['disease_id', 'disease_name', 'body_system', 'urgent_review_flag', 'source', 'note', 'pdf_page']

SYMPTOMS
['symptom_id', 'symptom_name', 'body_area', 'source', 'question_text', 'answer_type', 'source_note', 'pdf_pages']

DISEASE-SYMPTOMS
['disease_id', 'symptom_id', 'association', 'association_source']

MATRIX
['disease_id', 'disease_name', 'S001', 'S002', 'S003', 'S004', 'S005', 'S006', 'S007', 'S008', 'S009', 'S010', 'S011', 'S012', 'S013', 'S014', 'S015', 'S016', 'S017', 'S018', 'S019', 'S020', 'S021', 'S022', 'S023', 'S024', 'S025', 'S026', 'S027', 'S028', 'S029', 'S030', 'S031', 'S032', 'S033', 'S034', 'S035', 'S036', 'S037', 'S038', 'S039', 'S040', 'S041', 'S042', 'S043', 'S044', 'S045', 'S046', 'S047', 'S048', 'S049', 'S050', 'S051', 'S052', 'S053', 'S054', 'S055', 'S056', 'S057', 'S058', 'S059', 'S060', 'S061', 'S062', 'S063', 'S064', 'S065', 'S066', 'S067', 'S068', 'S069', 'S070', 'S071', 'S072', 'S073', 'S074', 'S075', 'S076', 'S077', 'S078', 'S079', 'S080', 'S081', 'S082', 'S083', 'S084', 'S085', 'S086', 'S087', 'S088', 'S089', 'S090', 'S091', 'S092', 'S093', 'S094', 'S095', 'S096', 'S097', 'S098', 'S099', 'S100', 'S101', 'S102', 'S103', 'S104', 'S105', 'S106', 'S107', 'S108', 'S109', 'S110', 'S111', 'S112', 'S113', 'S114', 'S115', 'S116', 'S117', 'S118', 'S119', 'S120', 'S121', 'S122', 'S123', 'S124', 'S125', 'S126', 'S127', 'S128', 'S129', 'S130', 'S131', 'S132', 'S133', 'S134', 'S135', 'S136', 'S137', 'S138', 'S139', 'S140', 'S141', 'S142', 'S143', 'S144', 'S145', 'S146', 'S147', 'S148', 'S149', 'S150', 'S151']

In [8]:
diseases = ml_datasets["diseases.csv"]
symptoms = ml_datasets["symptoms.csv"]
disease_symptoms = ml_datasets["disease_symptoms.csv"]
matrix = ml_datasets["disease_symptom_matrix.csv"]

print("Diseases:", diseases.shape)
print("Symptoms:", symptoms.shape)
print("Disease-Symptoms:", disease_symptoms.shape)
print("Matrix:", matrix.shape)

Diseases: (34, 7)
Symptoms: (151, 8)
Disease-Symptoms: (243, 4)
Matrix: (34, 153)

In [7]:
column_report = []

for filename, df in ml_datasets.items():
    duplicate_columns = int(df.columns.duplicated().sum())

    column_report.append({
        "file": filename,
        "duplicate_columns": duplicate_columns
    })

column_report_df = pd.DataFrame(column_report)

display(column_report_df)

                            file  duplicate_columns
0                   diseases.csv                  0
1                   symptoms.csv                  0
2           disease_symptoms.csv                  0
3     disease_symptom_matrix.csv                  0
4              question_bank.csv                  0
5              branch_starts.csv                  0
6          body_area_options.csv                  0
7   initial_routing_question.csv                  0
8               safety_rules.csv                  0
9           dataset_manifest.csv                  0
10         validation_report.csv                  0

In [6]:
duplicate_report = []

for filename, df in ml_datasets.items():
    duplicate_count = int(df.duplicated().sum())

    duplicate_report.append({
        "file": filename,
        "duplicate_rows": duplicate_count
    })

duplicate_report_df = pd.DataFrame(duplicate_report)

display(duplicate_report_df)

                            file  duplicate_rows
0                   diseases.csv               0
1                   symptoms.csv               0
2           disease_symptoms.csv               0
3     disease_symptom_matrix.csv               0
4              question_bank.csv               0
5              branch_starts.csv               0
6          body_area_options.csv               0
7   initial_routing_question.csv               0
8               safety_rules.csv               0
9           dataset_manifest.csv               0
10         validation_report.csv               0

In [5]:
null_report = []

for filename, df in ml_datasets.items():
    null_count = int(df.isna().sum().sum())

    null_report.append({
        "file": filename,
        "rows": len(df),
        "columns": len(df.columns),
        "null_cells": null_count
    })

null_report_df = pd.DataFrame(null_report)

display(null_report_df)

                            file  rows  columns  null_cells
0                   diseases.csv    34        7           0
1                   symptoms.csv   151        8           0
2           disease_symptoms.csv   243        4           0
3     disease_symptom_matrix.csv    34      153           0
4              question_bank.csv   150        8           0
5              branch_starts.csv    11        2           0
6          body_area_options.csv    11        3           0
7   initial_routing_question.csv     1        5           0
8               safety_rules.csv    14        5           0
9           dataset_manifest.csv    10        2           0
10         validation_report.csv    18        4           0

In [4]:
# The 11 AshaCare ML datasets we want to validate

ml_files = [
    "diseases.csv",
    "symptoms.csv",
    "disease_symptoms.csv",
    "disease_symptom_matrix.csv",
    "question_bank.csv",
    "branch_starts.csv",
    "body_area_options.csv",
    "initial_routing_question.csv",
    "safety_rules.csv",
    "dataset_manifest.csv",
    "validation_report.csv"
]

ml_datasets = {
    filename: datasets[filename]
    for filename in ml_files
}

print(f"Loaded {len(ml_datasets)} AshaCare ML datasets.")

Loaded 11 AshaCare ML datasets.

In [3]:
datasets = {}

for file in csv_files:
    try:
        df = pd.read_csv(file)
        datasets[file.name] = df

        print(
            f"✓ {file.name} "
            f"→ {df.shape[0]} rows × {df.shape[1]} columns"
        )

    except Exception as e:
        print(f"✗ {file.name} → ERROR")
        print(e)

✗ AshaCare_AI_questionnaire_symptom_map.csv → ERROR
No columns to parse from file
✗ AshaCare_AI_symptom_dataset_PDF_transcription.csv → ERROR
No columns to parse from file
✓ body_area_options.csv → 11 rows × 3 columns
✓ branch_starts.csv → 11 rows × 2 columns
✓ dataset_manifest.csv → 10 rows × 2 columns
✓ disease_symptom_matrix.csv → 34 rows × 153 columns
✓ disease_symptoms.csv → 243 rows × 4 columns
✓ diseases.csv → 34 rows × 7 columns
✓ initial_routing_question.csv → 1 rows × 5 columns
✓ question_bank.csv → 150 rows × 8 columns
✓ safety_rules.csv → 14 rows × 5 columns
✓ symptoms.csv → 151 rows × 8 columns
✓ validation_report.csv → 18 rows × 4 columns

In [2]:
csv_files = sorted(DATABASE_DIR.glob("*.csv"))

print(f"Found {len(csv_files)} CSV files:\n")

for file in csv_files:
    print(file.name)

Found 13 CSV files:

AshaCare_AI_questionnaire_symptom_map.csv
AshaCare_AI_symptom_dataset_PDF_transcription.csv
body_area_options.csv
branch_starts.csv
dataset_manifest.csv
disease_symptom_matrix.csv
disease_symptoms.csv
diseases.csv
initial_routing_question.csv
question_bank.csv
safety_rules.csv
symptoms.csv
validation_report.csv

In [1]:
import pandas as pd
from pathlib import Path

DATABASE_DIR = Path("../../database")

print("Database path:")
print(DATABASE_DIR.resolve())

Database path:
/workspaces/SIH-PROJECT/database